### ISSUE TITLE
Tracking current held positions after they are deselected from coin list

### ISSUE THREAD

**Issue by Mlecherr** [apex-trader/issue-tracker#1]
Hello, so I have been using the auto coin select feature (Top 75 quote) I normally select new coins throughout the day, the problem is when i'm holding a position and the coin is deselected the bot no longer follows that coin. Is there a way to make it so the bot will follow it and sell it? It will list its purchase price and current price still. EthMiner suggested I go back and add them to the list just so they will track. I did this, it worked for one bot, the other bot I had to actually add one coin to blacklist for the current positions to be tracked again. I'm running 2 bots, one is vypers OG, ETH with TSL the other is Bonekama, BTC, with TSL. If you need more info contact me on Discord. "melcher"

![apex](https://user-images.githubusercontent.com/42717326/44629725-ea4ca180-a918-11e8-9cac-1ab1d32c5f9b.png)

**Comment by willoughby** [comment]
Implemented and deployed
