### ISSUE TITLE
Positions dissapeared

### ISSUE THREAD

**Issue by davidbpm** [apex-trader/issue-tracker#10]
Hi Guys, my positions dissapear and do not come back after reboot: https://www.screencast.com/t/YEq3sPcl

it still looks like its all running in the background according to the logs

**Comment by davidbpm** [comment]
Vulcbot (binance-bot-1535286876965)

**Comment by davidbpm** [comment]
Other areas not loading too: https://www.screencast.com/t/mVi8q8e39d

**Comment by willoughby** [comment]
Looks okay now, @davidbpm contact us on our discord we could of solved this quicker
