### ISSUE TITLE
Ability to select multiple pairs to change strategy

### ISSUE THREAD

**Issue by magyosha** [apex-trader/issue-tracker#100]
It would be nice if we wanted to change strategy on multiple held pairs if there was the ability to do it using checkbox's on the pairs with a drop down for change strategy. 
it would make it easier to change all pairs from PT to PP and visa versa as we could have strategy per method and flick with ease between them on multiple pairs ...

**Comment by kyneh** [comment]
+1

**Comment by IEthMiner** [comment]
Coming in next update :)
