### ISSUE TITLE
Display PP % in open position

### ISSUE THREAD

**Issue by Mistras88** [apex-trader/issue-tracker#101]
Could you display the PP % under the Sell Conditions in an open position?   It currently only shows the Target.  I would like to see the actual percentage, such as 0.75%.   I'm often modifying my PP, but I don't want to have to take the calculator out and use the target number and do the math (I know, I'm lazy)   Displaying the set PP % number would be very handy.  Thanks!

-- Spitfire

**Comment by Bulfor** [comment]
That would be cool, and maybe also to change the pp directly :)

**Comment by willoughby** [comment]
done
