### ISSUE TITLE
strategy that lowers the PP based on length of time  a pair has been held

### ISSUE THREAD

**Issue by magyosha** [apex-trader/issue-tracker#103]
can we have a strategy that lowers the PP based on length of time  a pair has been held
eg 
newly bought - 2 hours  0.9%
2hrs - 4hrs  0.75%
4hrs - 8hrs 0.6% 
8hrs + 0.4%

**Comment by GarzCrypto** [comment]
Sounds great add on to me, I would also add the posibility to change the SL to what @magyosha suggests

**Comment by HYDRAXIII** [comment]
+1

**Comment by willoughby** [comment]
V1
