### ISSUE TITLE
No rebuild if new strat is the same

### ISSUE THREAD

**Issue by jangeisler** [apex-trader/issue-tracker#105]
On trigger event

**Comment by willoughby** [comment]
Your saying you are seeing this ?

**Comment by fredpook** [comment]
Yes, i have seen this too, specially when you have just started the trigger.

**Comment by Alexandros1234567** [comment]
+1

**Comment by willoughby** [comment]
Okay need some context in the future

**Comment by 4n1r0n** [comment]
+1

My settings make the bot switch strategies often, and the rebuilding slows it down substantially. Everly little bit helps...

**Comment by IEthMiner** [comment]
No more rebuilds, ever 👯‍♂️
