### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by 4n1r0n** [apex-trader/issue-tracker#108]
I would like to see a more condensed UI. Decrease the padding on all items, so it will be more glanceable and also quite a bit more mobile friendly.

**Comment by Kristofp** [comment]
The new message above the bot section takes up a lot of space on mobile devices.  Although the message itself is good it would be good if we could collapse it or if it would fade out and collapse after x amount of time.

**Comment by fredpook** [comment]
The text above the bots overview could just disappear when you have 1 or bots already.
