### ISSUE TITLE
Auto coin selection enhancement request

### ISSUE THREAD

**Issue by magyosha** [apex-trader/issue-tracker#112]
can we have ?
coin selection enhancement ..  something automated would be good .. so we do not have to keep changing the selection .. 
my example of my my selection .. 
exclude all coins by: (on btc)
lower volume than 30
lower price than 0.00000300 
percent movement less or greater than 7%

to accomplish this now i can choose the percent change pre selection option .. then the rest is manual clicking ,
i'd like to make these rules and have them applied automatically .

**Comment by IEthMiner** [comment]
Already raised https://github.com/apex-trader/issue-tracker/issues/70
