### ISSUE TITLE
Stochastic & Stochastic RSI indicator requests

### ISSUE THREAD

**Issue by Hivey** [apex-trader/issue-tracker#114]
I believe following enhancements to the Stochastic & Stochastic RSI indicators could be helpful

**Stochastic:** 
Add "Signal Below Overbought" option. Is available with most other indicators as well. Currently 3 available: "Signal Above Overbought", "Signal Cross Above Overbought", "Signal Cross Below Overbought"

**Stochastic RSI:**
Add "K Above D" & "K Below D" options. This can help to prevent triggering buys on a downtrend (when e.g. K went above set threshold for a second, as D would have changed as well)

Following 2 are also on my wish-list, but see there is a separate topic already for them :)

**Percent Change:**
Add Drop % to Sell Indicators. Currently only contains Rise %. Entering a negative % in the Rise % box will not work (say entering -1% would make it only sell on positive % or negative to 1%, but not on e.g. -2%)
Add Rise % to Buy Indicators. Same logic as above

**Bollinger Band Width:**
Some strategies won't work in a sideway market (hello MACD) and the BB Width seems a good indicator for that

**Comment by Alexandros1234567** [comment]
In my opinion the following would be helpful as well and give much more opportunities to build strats:

**Stochastic:** 
Signal above Oversold, K cross D, K above D, K below D,
(If possible the line direction: _When both Stochastic lines are headed in the same direction, they confirm the shortterm trend. When prices rise and both Stochastic lines rise, the uptrend is likely to
continue. When prices slide and both Stochastic lines fall, the short-term downtrend
is likely to continue._)

**Bollinger Bands:**
above/below middle band, Cross above/below middle band

**Macd:**
![image](https://user-images.githubusercontent.com/42898344/46869829-428a2500-ce2d-11e8-9d71-6a010b68a401.png)

**Comment by HYDRAXIII** [comment]
+1

**Comment by willoughby** [comment]
SRSI changes added to 0.11

**Comment by willoughby** [comment]
Percent Change modification added to 0.11
