### ISSUE TITLE
Problem with TA selling when using StochRSI

### ISSUE THREAD

**Issue by Crypticgun** [apex-trader/issue-tracker#115]
There seems to be a problem with StochRSI when using the TA selling option. If used 'k cross below d' and simultaneously 'k above overbought' some sells will be missed. Also the 'k cross below d and overbought' seems not to work properly.

**Comment by willoughby** [comment]
@Crypticgun do you have examples of this

**Comment by Crypticgun** [comment]
Hello,

I discovered when using stochRSI and wanting that coin to be sold with k below d and simultaneously this action performing over a certain threshold the function ‚k below d and overbought‘ inhibits the TA selling. I ‚ve tested this multiple times.
I helped myself by adding another stochrsi indicator with selecting only  the ‚overbought‘ field . This works for my purpose. Maybe I understand this function ‚k below d and overbought‘ wrong. 

Thanks,
Gunter
