### ISSUE TITLE
Feature request: Shorting exactly as it done now ad CH

### ISSUE THREAD

**Issue by hikaru0022** [apex-trader/issue-tracker#118]
I really enjoy latest beta feature of CH - shorting, guys could it be done at apex?
it's absolutely crazy stuff to trade some hand picked coin through second bot as example, when first one will run general strategy, second bot just will run few coins with shorting ability

**Comment by IEthMiner** [comment]
Hi @hikaru0022 

Shorting will a feature available via Apex and will be a feature released after the 'Auto DCA'

Many thanks
