### ISSUE TITLE
Feature Request: PAX as base currency

### ISSUE THREAD

**Issue by jat73** [apex-trader/issue-tracker#121]
As USDT is having trouble and is hasn't been the most reputable stable coin due to concerns with the backing of USDT / USD, can we also have PAX as base currency to trade? Binance currently supports a few pairs and will most like expand that list.

**Comment by willoughby** [comment]
PAX has not been added as a base yet, just a pair to the current bases

**Comment by IEthMiner** [comment]
Hi @jat73 

Binance don't currently support PAX as a base currency but if they do in the future this will be looked into.

When Apex is available on KuCoin PAX will be a base currency availablein Apex

Many thanks
