### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by mreddiefercury** [apex-trader/issue-tracker#122]
there are too many types of source. like open, close, high, low etc. apex uses 'close' as a source but i think we have to choose what we want. tradingview has an option for this and apex should add this stuff. sorry for bad english.
![djk](https://user-images.githubusercontent.com/42179086/47011293-40d0a200-d14a-11e8-8d18-79091173f1e2.png)

**Comment by IEthMiner** [comment]
Hi @mreddiefercury 

I believe 'hlc3' will get you the closest to Apex when using Trading View 

Thanks
