### ISSUE TITLE
Easy limit sell button

### ISSUE THREAD

**Issue by IEthMiner** [apex-trader/issue-tracker#124]
ramakuzeraToday at 22:22
yo @EthMiner , do you think it would be possible to have a easy accessible button that takes the current price for a position and instantly puts it out on a limit sell?

**Comment by 4n1r0n** [comment]
I agree... I do this manually often. It would be useful. Like the market sell button, but using the current price as a limit sell order.

**Comment by willoughby** [comment]
Added and done 👍
