### ISSUE TITLE
Bollinger Band should have more option

### ISSUE THREAD

**Issue by mrbollinger** [apex-trader/issue-tracker#131]
I want to buy at only upper side of bollinger bands upper band. When i add a buy indicator select bollinger band and choose "price above", it is price above the "lower band". but i want to buy above "upper band".

if you add this, we will solve the volatility problem on altcoins. because everybody wants to trade at bullish market. if you add this option, we will find the bullish markets easily

thank you

![aaa](https://user-images.githubusercontent.com/44550358/47618190-d8ce7400-dad8-11e8-9ef6-918ebe7a475f.png)

**Comment by Alexandros1234567** [comment]
+1

**Comment by willoughby** [comment]
You could try a negative deviation to do this

**Comment by Alexandros1234567** [comment]
If puppy therapy's bb madness work same like apex, it doesn't work.

**Comment by Francoisp5** [comment]
We should be able to select upper and lower BB on both nuy and sell indicator...

**Comment by willoughby** [comment]
I don’t know what that is

**Comment by Alexandros1234567** [comment]
What?

**Comment by mreddiefercury** [comment]
+1

**Comment by willoughby** [comment]
closing for now as you have a workaround
