### ISSUE TITLE
K Above D and K below D in SRSI indicator

### ISSUE THREAD

**Issue by Francoisp5** [apex-trader/issue-tracker#133]
Hello, I would like to have the option to select K above or below d on SRSI indicator instead of just the cross above please :) thanks

**Comment by HYDRAXIII** [comment]
+1 agree :)

**Comment by willoughby** [comment]
@Francoisp5 will be in 0.11.0b

**Comment by Francoisp5** [comment]
Thanks :)

Envoyé de mon iPhone
