### ISSUE TITLE
Raised on behalf of Jeffrey Pisarek

### ISSUE THREAD

**Issue by IEthMiner** [apex-trader/issue-tracker#138]
Jeffrey Pisarek
Today 05:09

Hi,

I'm not sure the best way to make suggestions for improving the bot, here or on Discord. The ability to integrate with TradingView for coin selection is fantastic.

I would like to suggest allowing users to pick "Sell" and "Strong Sell" rated coins, too. I know Binance doesn't allow you to short. But being able to pick these coins could allow one to buy the dip on a long time frame. You could add a disclaimer saying that choosing coins with a Sell or Strong Sell rating is a risk.

**Comment by willoughby** [comment]
Added to the list
