### ISSUE TITLE
Only sell with profit for Sell Based on TA?

### ISSUE THREAD

**Issue by joecrypt0** [apex-trader/issue-tracker#141]
Only sell with profit for Sell Based on TA would be very helpful. I think it would maximize profits while reducing bags.

**Comment by HYDRAXIII** [comment]
+1

**Comment by willoughby** [comment]
done, 

![image](https://user-images.githubusercontent.com/158088/48867169-39e22280-edcd-11e8-8714-17f3616b50a4.png)

**Comment by joecrypt0** [comment]
Amazing! Thanks!
