### ISSUE TITLE
CSV export enhancements

### ISSUE THREAD

**Issue by Kristofp** [apex-trader/issue-tracker#148]
Some enhancements to the CSV data

1. Currently the **Close price** is not shown in the CSV
2. Timestamp in a more readable format, maybe addition of an "**Exposure time**"
3. **Link to the chart** so you can directly go the chart from the excel sheet by clicking on the link.
4. Format the CSV using "**;**" instead of "**,**" for easier import into Excel or Numbers

**Comment by willoughby** [comment]
done
