### ISSUE TITLE
Trigger to change back to default didn't work

### ISSUE THREAD

**Issue by Bonefire1** [apex-trader/issue-tracker#15]
Am running a version of Venom triggers (added few more candles to the buy indicator).... with the BTC spike yesterday the trigger worked and switched the strategy to bullish....but after cool-down when no signal came it failed to switch back to the default sideways strategy (was stuck in bullish).

**Comment by willoughby** [comment]
Need more information when something doesn't work. I'm not familiar with all the strategies people run.
