### ISSUE TITLE
Indicators to add

### ISSUE THREAD

**Issue by Alexandros1234567** [apex-trader/issue-tracker#153]
As discussed in Discord, please add the following indicators if possible:

![image](https://user-images.githubusercontent.com/42898344/49312362-401a8200-f4e4-11e8-8df3-153e2c1b1994.png)

https://www.tradeciety.com/how-to-choose-the-best-indicators-for-your-trading/

**Comment by Kristofp** [comment]
Williams % and Ichimoku Cloud plz!

**Comment by willoughby** [comment]
Williams, Ichi, ADX, Parabolic SAR, ADX and ATR added

**Comment by willoughby** [comment]
Standard Deviation added
