### ISSUE TITLE
Fees on negative closed position

### ISSUE THREAD

**Issue by Leite1** [apex-trader/issue-tracker#154]
When a position is closed at a loss, the fees are not being added to increase that loss. At least in test mode.

![1](https://user-images.githubusercontent.com/45511927/49327845-59601480-f55e-11e8-933c-60addb03dcd6.png)

![2](https://user-images.githubusercontent.com/45511927/49327850-6250e600-f55e-11e8-90b9-3a8a708fd76c.png)

**Comment by willoughby** [comment]
fee issues resolved in 0.11
