### ISSUE TITLE
Shorting feature on SL and Triggers?

### ISSUE THREAD

**Issue by joecrypt0** [apex-trader/issue-tracker#159]
When shorting is eventually added can we have it as a trigger option (like panic sell) as well as an option under Stop Loss?

**Comment by joecrypt0** [comment]
I would just put an option to short instead of sell based on TA and short
instead of stop loss just like you have an only sell with profit option in
TA now. Then for triggers I would add the option to short all positions so
I can do that instead of panic sell. To close a short position (buy back
in) you will need a separate section to select trailing stop short,
percentage profit, and TA, like cryptohopper.

**Comment by willoughby** [comment]
We have something coming in V1
