### ISSUE TITLE
% spilt compound between reserve and position

### ISSUE THREAD

**Issue by ulvenk** [apex-trader/issue-tracker#170]
Hello. Another request: when compound- let us have a % split compound between reserve and position

**Comment by kyneh** [comment]
I have the same problem that the compound normal allocation increases too high that the reserved allocation for DCA is actually not enough any more. 

Maybe another approach is that we can define the total allocation for the bot and then define the ratio for normal/DCA allocations. So it's also easier to calculate the compound allocation

**Comment by willoughby** [comment]
this is handled in v1 for you, the bots knows the ratio based you your allocation setup
