### ISSUE TITLE
Feature Request:  Trade Schedule/ On/Off Buying

### ISSUE THREAD

**Issue by kingofkrypto** [apex-trader/issue-tracker#179]
Generally after 5PM ET on weekdays, and all day on weekends SAT/SUN- there tends to be low volume.  Sundays are blodbaths as we have seen, and not everyone can dedicate so much time to trading when we are working our day jobs, or spending time doing other things- living life. 

Please, for the love of crypto- create a schedule for turning Buying ON AND OFF based on day and time.  I would have weekdays after 5PM off as well as weekends.  Just like the regular markets.

**Comment by willoughby** [comment]
You can do this in v1
