### ISSUE TITLE
Coin Selection Process

### ISSUE THREAD

**Issue by jat73** [apex-trader/issue-tracker#18]
My ideal coin selection process would have the following filters / selection fields:

1. Number of coins
2. Order by (volume, volatility / percent change etc.)
3. Only select positive pairs (optional checkbox)
4. Append coins in positions (optional checkbox)

**Comment by Glyxbringer** [comment]
In addition to what jat73 suggested

I would like to have a filter or selection field in the coin selection area that shows me if I have an open position of that coin with that bot.
So when adjusting the traded coins in terms of top whatever quote or volume you can easyly keep track if you should uncheck a certain coin or not.

**Comment by jat73** [comment]
Maybe we could have a coin selection tab next to settings to save our custom coin lists, like "my favorite 15 coins" or "perspective high flyer 20" etc. 
And also have the blacklist under the same tab so see our coin lists and blacklist in one place.
And next to each saved list we'd see if that list was applied to a bot.

**Comment by IEthMiner** [comment]
https://github.com/apex-trader/issue-tracker/issues/70 

Added to coin selection tick
