### ISSUE TITLE
binary.com bot - Plz help to add stop loss and take profit 

### ISSUE THREAD

**Issue by duyorion** [apex-trader/issue-tracker#184]
Hello friends,

The attached is 6066 bot I got from @lasaidhari. I want to add stop loss and take profit in (I did it but it did not seem to work).

[binary-bot_6066_v3.0.zip](https://github.com/apex-trader/issue-tracker/files/3045926/binary-bot_6066_v3.0.zip)

Please help me in this case so that I can add sl and tp by myself for other bots.

Thank you and have a nice day!

duyorion.

**Comment by IEthMiner** [comment]
Please do not add zip files. Unfortunately files like this cannot be trusted and for anyone viewing this please do not download!

@duyorion please discuss sl and tp in our discord
