### ISSUE TITLE
Split and merge positions

### ISSUE THREAD

**Issue by 4n1r0n** [apex-trader/issue-tracker#19]
Like CH to have more fine grain control of bag management. Unless the anti bag feature comes earlier that is.

**Comment by IEthMiner** [comment]
This is en route 👍

**Comment by 4n1r0n** [comment]
Shouldn't this be moved to 1.0 ?

**Comment by 4n1r0n** [comment]
and reopened? :-) Sorry to nag, but i'm really eager for this :p

**Comment by Chipply** [comment]
Is the ability to split a position still in development/possibly available in the future?
