### ISSUE TITLE
Blacklist Feature

### ISSUE THREAD

**Issue by jat73** [apex-trader/issue-tracker#20]
I would love to see a separate blacklist tab next to the settings tab where I can list the coins I don't want to buy. Ideally, I could name and save different blacklists, much like the strategies. 
That way a blacklist could be applied to multiple bots and whenever I want to add a coin to the blacklist, I could just edit the blacklist and all bots would refrain from buying that coin.

**Comment by IEthMiner** [comment]
added to coin selection tick - https://github.com/apex-trader/issue-tracker/issues/70
