### ISSUE TITLE
[feature request] open position manually

### ISSUE THREAD

**Issue by jabbalaci** [apex-trader/issue-tracker#206]
It would be nice if I could open a position manually. Then, the bot would take control of it and everything would go on as if the bot had opened it.

Motivation: I have a strategy that gives a positive buy signal when the wave trend is low (similar to the default Black Magick V1). However, when you browse Tradingview, often the price is going up but the wave trend is high and the strategy won't give a buy signal. In this case it would be nice if I could "hack" the strategy and make it give a positive buy signal.

Where to add it? It could be at the indicators. At the moment, Apex Trader shows the state of the strategy: which conditions are true / false. Here we could have a "Manual Buy" button that would set all conditions to true, thus the strategy would signal a True sign and the bot would open the position. From this moment on, the bot would control everything, as if it had opened the position normally.

How to use it? You browse Tradingview and you see that a coin's price is going up nicely. You check the bot and you see it didn't buy this coin. Then you could open a position manually.

**Comment by willoughby** [comment]
Apex has  manual buy already built in positions tab > actions button > manual buy

**Comment by jabbalaci** [comment]
Thanks, but how does it work? If I click on it, I get an empty page.

At the moment my list of open positions is empty. Say I want to buy ADA/USDT. Clicking on actions button > manual buy should let me buy it?

**Comment by willoughby** [comment]
Should open a popup and you choose the coin, investment amount and strategy to sell with

**Comment by jabbalaci** [comment]
Strange. Under Firefox (using Linux), I get an empty page. There is no popup.

**Comment by willoughby** [comment]
Open a support ticket
