### ISSUE TITLE
Suggestions for the Strat Center

### ISSUE THREAD

**Issue by Glyxbringer** [apex-trader/issue-tracker#21]
it would be nice to have a field or a tag or a filter to indicate the Base currency that the strategy was made for
In addition there could be something indicating if it works for other currencys too..

Example

Le Millefeuille v1.1
created by Pat Le Patissier
Dowloads ........
Designed for BTC
Other tested currencies  - not testet yet

**Comment by Glyxbringer** [comment]
Another Idea would be to setup a Testbot on your end for the Top 25? choose whatever you like Strategys, and have a link to the results of those strategies..
would be awesome I think

**Comment by willoughby** [comment]
v1
