### ISSUE TITLE
Panic tether

### ISSUE THREAD

**Issue by AuroriSwe** [apex-trader/issue-tracker#22]
An option for a trigger to activate a panic tether, making it possible to liqudice funds before a drop. Possibly add a rebuy function for a set percentage as well

**Comment by filipcourtois** [comment]
would be nice!

**Comment by Glyxbringer** [comment]
+1 
and would like to have a botton for that too... not only as a trigger...

**Comment by artificialkunyi** [comment]
You can Buy Tusd From Ethereum/Bitcoin base currency, its like tether, and no need change your base currency, maybe with more Activ Triggers you can do this

**Comment by AuroriSwe** [comment]
Buying TUSD is basically the same as buying USDT but I still have to do it manually, I'd like a trigger to instead of just panic selling, panic sells and then sells my ETH to USDT and then preferably buys it back after the drop

**Comment by urnzwy** [comment]
Panic to Tether and buy back would be amazing. Could be gaining on these dips of your base currency is a chance I'd be willing to take.

**Comment by willoughby** [comment]
Panic to tether and buy back implemented
