### ISSUE TITLE
Please add automated Dollar Cost Averaging (DCA) like CH

### ISSUE THREAD

**Issue by hms2ms** [apex-trader/issue-tracker#23]
Please add automated Dollar Cost Averaging (DCA) like CH.
We really need this guys in-order to leave CH and concentrate here.
Thanks

**Comment by IEthMiner** [comment]
Our next big release will be containing this 

Thanks

**Comment by urnzwy** [comment]
Yaaaaaaas I want this so bad!

**Comment by 4n1r0n** [comment]
Preferrably, implement this like PT Defender, NOT like CH (Configurable dilution method with buy triggered by (seperately configurable) TA)

**Comment by HYDRAXIII** [comment]
+1

**Comment by IEthMiner** [comment]
Auto DCA is on the way :)
