### ISSUE TITLE
Indicators tab for strategies not yet assigned to bot

### ISSUE THREAD

**Issue by mgoblue33** [apex-trader/issue-tracker#233]
It would nice if we could have an indicators tab that shows all the coins that are ready to buy or sell based upon the strategy we have setup.  Right now, that tab only works if the strategy is assigned to a bot.   I have multiple strategies I have created and I would like to see this tab for all my strategies, BEFORE I assign the strategy to the bot.  Or add all the strategies we have to this tab so we can click back and forth on all of them, instead of just seeing the one connected to the bot.   I would use this to determine which strategy is best for that time I am looking etc...

**Comment by IEthMiner** [comment]
Add them into a single strategy use separate groups for each. 

Some users have dozens of strategies. The information call would be huge 

Closing
