### ISSUE TITLE
Add BTC to buy/sell strategy

### ISSUE THREAD

**Issue by mgoblue33** [apex-trader/issue-tracker#243]
I know this might sound crazy, but is it possible to add a BTC strategy to an overall strategy for both buy and sell.  For example, I create a simple MACD cross above MACD Signal on the 5M for buy and MACD cross below MAC Signal for the sell and I use this on my USDT bot.   I would like to add a condition within the buy and sell strategy that the BTC MACD be above MACD signal as a criteria for buying any altcoin and the BTC MACD be below MACD signal for my sell strategy to activate or something.    

Since BTC is king, having this added would be a huge feature since many coins follow what BTC does.  I realize it won't apply in all situations and could cost false buy/sells, but I would love to see it added as an option for people who want to include it into their strategy. I would definitely use it.

**Comment by IEthMiner** [comment]
If I understand what you're trying to say this can already be done.

Create 2 strategies under the automation tab in My Strategies 

Under the  automation tab in your bot and create rule and select "Strategy" as the type  , select btc usdt as the pairing on the rule and choose your MACD strategy (buy side first) 

When the rule is created add actions to it which will be buy enabled, sell enabled and any others you may want 

Follow the same process for the sell side.
