### ISSUE TITLE
Auto Track and Auto Buy BNB Before Amounts Run Out (from CryptoManiac)

### ISSUE THREAD

**Issue by paranormalrob** [apex-trader/issue-tracker#28]
Feature Request

Give the bot the ability to calculate fees differently based on whether the user has BNB balance or not and it could be included in our results.  It already knows how much BNB we have.

Maybe have something above the menus or somewhere where it gets our attention that shows our BNB balance. Then have it in green for 2+ BNB, Yellow for 1-2, red for less than 1.  Maybe even add a popup or email when its less than 1 or 0.

Add to that, someone else had the idea of the option to auto-buy $X amount of BNB when it gets to a particular chosen amount.

A nice add-on that would save people money. Or it could be an option in settings.

Of course, disable it if BNB is the base.

**Comment by Alexandros1234567** [comment]
Best would be in my opinion the following:

Set BNB threshold -> Balance falls below threshold -> Buy set amount BNB -> Recalculate Total Allocation Base/Send mail as information to user (if wanted) -> Balance falls below threshold........

**Comment by willoughby** [comment]
Coming in V1
