### ISSUE TITLE
Subscription to Triggers/Strategies of others

### ISSUE THREAD

**Issue by dgilbert002** [apex-trader/issue-tracker#32]
created by Dettori:

why not create a setup on Apex that allows people to implement your (or other) strategy EXACTLY as you're doing it... if you change/update, it changes and updates everyone following you.... and maybe even a % of profits into your wallets or to support development (whichever)

Would be great as it allows almost a "managed" strategy for people who want to use the platform, increases the profits (hopefully) for people with day jobs, but incentivises the people with strategies to maintain them for profit? If there's a market loss and the bot's not performing well ... means loss of income for the strategy owner, and... well... there's always a risk, so the end user or follower waivers the owners responsibility for the loss...

**Comment by willoughby** [comment]
Yeah we are modeling this in for the future, VenomX will be the first

**Comment by willoughby** [comment]
Coming in v1
