### ISSUE TITLE
Arm a new TSL manually for an open position

### ISSUE THREAD

**Issue by 4n1r0n** [apex-trader/issue-tracker#36]
Add a button in the position journal (next to limit and DCA) to reset or manually set a TSL. 
That way you can lock a loss or a profit of a position down manually while still trailing upwards if it has upward momentum.

I would use this on a bag that for example has seen a range of -0.80% to -5% (3 times).
Next time it would hit for example -1% I could manually lock that loss down, so I don't have to go down to -5 or worse again.
Alternatively it can work with profits as well when your running PP. (PP of 1.2, hovering for a while at 0.5, lock the 0.5 profit down, and trail upwards if possible, or sell off).

In CH you could accomplish this by removing and resyncing the position and set the pp or TSL manually.

**Comment by fredpook** [comment]
+1

**Comment by magyosha** [comment]
+1

**Comment by willoughby** [comment]
You can now assign a new sell strategy
