### ISSUE TITLE
Please add  STOCHRSICRSICROSS 

### ISSUE THREAD

**Issue by srp106** [apex-trader/issue-tracker#39]
I did not find the indicator STOCHRSICRSICROSS ! Could you please add this indicator , if possible. ! @vas2201

**Comment by willoughby** [comment]
![image](https://user-images.githubusercontent.com/158088/45178399-7ca04f80-b20d-11e8-8d65-78ea41b856e1.png)

This is what you want to use

**Comment by vas2201** [comment]
Could you please confirm K Cross Above D and Oversold is stochrsicross  ?.

This is following the indicator that I was asking for and also please add for the same indicator for buying too! 

https://wiki.profittrailer.com/doku.php?id=buy_and_sell_strategies#stochrsicross

https://wiki.profittrailer.com/doku.php?id=indicators.properties#stochrsicross_cross_candles

Thank you

**Comment by willoughby** [comment]
Use the K Cross Above D, Apex reacts in realtime so when it crosses it emits a signal. I can't see a reason for us to need to check if it crossed in the last x candles

**Comment by vas2201** [comment]
Okay, Thank you for the info! I would like to use this indicator as following for buying and selling! 

Buy : 

BuyStrategy: stochrsicross  
Buy value : 0.05
Buy Value limit : 20

Sell : 

Sell Strategy: stochrsicross 
Sell value : -0.05 

How can I set-up these two settings in my strategy?. This is more powerful if I use with Gain and  RSI. 

Thank you !
