### ISSUE TITLE
Automatically change between TSL and fixed %!

### ISSUE THREAD

**Issue by dhole01** [apex-trader/issue-tracker#45]
I want a function that uses a higher percent profit with TSL for the first hour a position is open, then transitions it to a fixed lower sell percent.

These boots tend to miss some money on new positions that sell quickly, this might help the issue.

**Comment by urnzwy** [comment]
Genius idea.

**Comment by filipcourtois** [comment]
+1

**Comment by willoughby** [comment]
You can now switch sell strategy
