### ISSUE TITLE
Coin Selection Suggestions

### ISSUE THREAD

**Issue by Mlecherr** [apex-trader/issue-tracker#5]
2 suggestions for coin selection.

One, if a coin is on your black list it will not be selected when you do auto select.

Two, having the option to exclude new coins to the exchange. Example, coins must be X amount of days old.

**Comment by IEthMiner** [comment]
A blacklist coin may still show it's selected though it will not buy, this is just to track the coin for selling

**Comment by IEthMiner** [comment]
we do that automatically now so you  don't need to select

**Comment by IEthMiner** [comment]
Second request included in here https://github.com/apex-trader/issue-tracker/issues/70
