### ISSUE TITLE
Stop loss and profit percentage

### ISSUE THREAD

**Issue by DolceAmerica** [apex-trader/issue-tracker#51]
Please make an easy way to adjust these parameters without creating a new bot.
Thank you 👍

**Comment by willoughby** [comment]
a new bot? you mean strategy?

**Comment by DolceAmerica** [comment]
Yes. Just a simple way to change in settings.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by willoughby** [comment]
done
