### ISSUE TITLE
BTCUSD Course Trigger.

### ISSUE THREAD

**Issue by Kirk1965** [apex-trader/issue-tracker#52]
Will it be possible to make a function for Trigger, say all buy stop and all buy go at a specific/range btc course. This way you don’t haft to rely on indicators or procentage to meet the trigger. Side ways ex. between 6100 and 6300 btc. Or you think BTC will go up and the course is 6300usd, and you will trade from 6350 to 6500 and stop trade if BTC goes below 6350usd. I rather miss a opportunity than loos..

**Comment by willoughby** [comment]
in v1 yes
