### ISSUE TITLE
Enhancement for Buy Detectors RSI/SRSI/Stoch

### ISSUE THREAD

**Issue by Puppytherapy** [apex-trader/issue-tracker#56]
Hey guys i hope i am not bothering i would like you to think about following additions to buy strategy detectors.

Stochastic RSI:
- K Above Oversold (sometimes coins stay oversold for a long period of time therefore its good to trade the mid range thus this)
- K is rising (Very interesting area to trade in is when SRSI is rising and between Oversold and Overbought on a bigger timeframe)
-Maybe to make it easier you can define Oversold / Overbough instead of just Oversold

Stochastic and RSI:
- Introducing both Oversold/Overbought here would also be beneficial

**Comment by Puppytherapy** [comment]
Price Change
 -Now you can only add Drop what if i want to buy uptrend or i want to buy anything with an above zero price change in the last 1 hour etc

**Comment by willoughby** [comment]
Use a negative

**Comment by Puppytherapy** [comment]
I mean i want to be buying coins with a positive price change in the last 30 minutes or an hour. Basically i want coin with 0 or above price change in the last 30 minutes or an hour is it possible ?

**Comment by IEthMiner** [comment]
Try a positive value in there, not sure if this will work... Was going to test the other day but didn't get round to it... Let us  know :)

**Comment by Puppytherapy** [comment]
It will not work as i want it to it takes the positive number and works with it but it check if the change is smaller than. I think it would be good to add a switch to be able to select both (Smaller than / Bigger than) :)

**Comment by Puppytherapy** [comment]
Also would be good to implement divergence plays :)

**Comment by fredpook** [comment]
+1
I have been searching for a successful sell on TA and RSI divergence looks very promising.
There many juicy +5% - +7% gains to be had with something like:

https://www.tradingview.com/script/42wcFfql-Relative-Strength-Index-Divergences-Libertus/
