### ISSUE TITLE
"Bots" Page performance quick view.

### ISSUE THREAD

**Issue by urnzwy** [apex-trader/issue-tracker#58]
Add the performance for say the past 7 days to the Bots page. So if you are running multiple bots, you can view the performance without opening the bot.

The current summary from the positions page would be great to have there as well.

Picture for reference

https://media.discordapp.net/attachments/453949013108981770/489461765835325440/Apex3.png?width=1200&height=482

**Comment by Mistras88** [comment]
That's a great idea - +1 from me!
