### ISSUE TITLE
Max profit 

### ISSUE THREAD

**Issue by Mlecherr** [apex-trader/issue-tracker#6]
Request to add max profit along side TSL. PT had this and it helped to avoid getting hit with pump and dumps. 
Example TSL arm is at 1.5% but with a max profit set to 5%, once the position hits 5% it will sell no matter what. This helped me avoid some bad bags in PT would be great to see here.

**Comment by filipcourtois** [comment]
seconded

**Comment by IEthMiner** [comment]
Hi @Mlecherr 

This will be added as a later feature - For the moment you can enable 'Sell on TA' in your strategy and select the 'Percentage Change' indicator to 5% change. This will currently do what you want.

Feature to be added at a late date 

Thanks !

**Comment by IEthMiner** [comment]
Can be achieved with the above comment
