### ISSUE TITLE
Add the option to choose if Panic Sell uses Market or Limit order in settings.

### ISSUE THREAD

**Issue by 4n1r0n** [apex-trader/issue-tracker#62]
That way, Panic Sell can be used in emergencies with Market, but I also would like an option to Liquidate at current Limit rates, because market slippage can really hurt. Maybe even an extra button that you can press multiple times if necessary (if prices do slip).

Or even better a liquidate button on the journal of a position, to do what I just described.

**Comment by willoughby** [comment]
Manual option is available to do this in 0.11
