### ISSUE TITLE
Less Than Percent Change

### ISSUE THREAD

**Issue by BlazefuryX** [apex-trader/issue-tracker#73]
Would it be possible to add an option for less than the percent change? I would like to use it to prevent the bot from buying pumped coins.

**Comment by BlazefuryX** [comment]
Please disregard. I realized later that it works the way I want it to when putting in a positive number.

**Comment by bmatusiak** [comment]
https://github.com/apex-trader/issue-tracker/issues/87

**Comment by bmatusiak** [comment]
yes it does work,, but only for -% drops, but it does not work for above -%

**Comment by willoughby** [comment]
duplicate
