### ISSUE TITLE
On behalf of Bonfire_1

### ISSUE THREAD

**Issue by IEthMiner** [apex-trader/issue-tracker#76]
Working name :Alts-gainer

This was a request on the other platform we used to track requests in, just putting it here as well.

For people that would like to grow their favorite alts holdings (XML, TRX, BAX...) it would be beneficial to have an option in the bot where the bot would not cash out a set profit percentage as the base currency rather leave that on the exchange as the surplus alt.

Bot buys XML worth 1ETH, position grows by 1%...bot sells the position leaving 0.85% (1% - binance fees) on exchange as XML basically giving you back the 1ETH so you can repeat the process...

**Comment by 4n1r0n** [comment]
+1

**Comment by Mistras88** [comment]
Great idea! +1

**Comment by willoughby** [comment]
you can do this with ART
