### ISSUE TITLE
Logo on black screen

### ISSUE THREAD

**Issue by orchiddoug** [apex-trader/issue-tracker#78]
Woke up to the new update, loved it.  Then it went away and changed to the logo with three dots pulsing... but it's been like that now for what seems to be almost an hour.  Normal??? updating?   Does it really take that long to update?

**Comment by IEthMiner** [comment]
No it shouldn't .. Can you Ctrl + F5 and refresh

**Comment by orchiddoug** [comment]
OK... right after I posted this... I logged out and re-logged in, and now it's back again.  I wonder what happened... hmmm.....

**Comment by IEthMiner** [comment]
Ah okay, that's fine. Thanks :)
