### ISSUE TITLE
Feature Request: Option to enable/disable trade sound

### ISSUE THREAD

**Issue by Alienpups** [apex-trader/issue-tracker#85]
I love this sound but sometimes it would be helpful to have an option to enable/disable it. That's also a smaller feature/fix, but would help a lot too :)

**Comment by bmatusiak** [comment]
if you use chrome... you can right click the TAB and click "Mute Site"

**Comment by IEthMiner** [comment]
https://github.com/apex-trader/issue-tracker/issues/9

Duplicate

**Comment by Alienpups** [comment]
lol. smart fix. thx.
