### ISSUE TITLE
Percent Change - Indicators 

### ISSUE THREAD

**Issue by bmatusiak** [apex-trader/issue-tracker#87]
Please fix Percent Change Indicators, it needs to have a `drop down` with, `Above` and `Below`, and the `Percentage`,  

`Drop %`  is there.. with a box with default -5  ...   and this does not work correctly if i want to use a coins that is going up withing a given time frame... 

thanks..

**Comment by bmatusiak** [comment]
@willoughby  one idea for possible faster fix,   is to create a new indicator called "Percent Change Above" because the current Indicator is technically called "Percent Change Below"

**Comment by willoughby** [comment]
It’s really a fix, we will do it properly we’re in no rush

**Comment by willoughby** [comment]
added to 0.11.0b
