### ISSUE TITLE
Different sound effect when selling at loss

### ISSUE THREAD

**Issue by kyneh** [apex-trader/issue-tracker#9]
Can we change a different sound effect for a stop loss sell? It's a bit disappointed to receive a chi chang but seeing a position was sold in a loss

**Comment by orchiddoug** [comment]
I would like to have a different sound effect as well AND also ADD that it would be nice if the POPUP was RED instead of green when showing there was activity, but that activity was a loss.

**Comment by willoughby** [comment]
done in 0.11
