### ISSUE TITLE
New Indicator - BB Width

### ISSUE THREAD

**Issue by Puppytherapy** [apex-trader/issue-tracker#90]
Dear Devs,

would it be possible to add BB Width as a new indicator. I have made an exampe script for PT https://www.tradingview.com/script/57omujLt-PT-Bollinger-Bands-Width/

You are already doing the calculation and receiveing the following data bottom / top / mid. The calculation is at follows.
bbwidth = ( top - bottom ) / mid

Why i feel its a good indicator. You can avoid buying coints that you would be holding for hours without movement or pump and dump scenarios if you were to be able to select a min max value for it it would be amazing.

**Comment by HYDRAXIII** [comment]
+1

**Comment by kyneh** [comment]
+1

**Comment by jangeisler** [comment]
+1
PLEASE make this. It could even be in % with no regards to the actual price.
Could be something like ((top - bottom) x 100) / price = x%

Would make it full auto to pick an exact level of volatility, like "15m candle, 25 periods, less than 6% but more than 3%".

**Comment by willoughby** [comment]
Implemented in V1
