### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by bmatusiak** [apex-trader/issue-tracker#96]
i need a API so i can build a smartphone monitor app,
and to build my own personal experimental features

read access would include
14 Day Summary Data
Open Position Data  
BTC Estimated Value

write access would include
set/change   BUY/START/TRIGGER  status 
panic selling

that would get me started with a community app for andorid devices 

this would also allow me to track and build my own statistics that may not be useful to others, but not limited to others.

the main idea for me is to have a Notification Tab of the status of the bots in my phone.

**Comment by willoughby** [comment]
We're already working on one

**Comment by bmatusiak** [comment]
well let me know, i will be interested in testing, i really want to stay on top of my bots because the beta service is costly to me and i want to save as much as i can while helping and supporting apex-trader

**Comment by IEthMiner** [comment]
In what regards is the beta service costly to you?

**Comment by bmatusiak** [comment]
@IEthMiner this is not the place to talk about my personal finance, sorry if you took that out of context
