### ISSUE TITLE
Sell on TA setting overiding "Amend Sell Strategy"

### ISSUE THREAD

**Issue by neilAllcoast** [apex-trader/issue-tracker#97]
It does not make sense to have a global setting override an "Amend" command. Maybe I want to not sell a coin on a TA. Maybe I am in a bag with a coin that I can see Holding, so I want to make sure that it does not get sold before a chance to have the price rebound. If you are allowing people to  "Amend Sell Strategy" ON THE FLY, then that should override ALL sell strategies assigned to that position. Including the default one assigned. Also, maybe a note should have been added that "amending a sell strategy" does not completely amend the selling strategy if using "sell on TA"

This is based on being informed that "Sell on TA" overrides any other sell command set via the position option.

**Comment by formerminer1** [comment]
I like the idea of being able to disable Sell on TA so that I can DCA a bag if I wanted to - before the TA trips and the bag sells.

**Comment by willoughby** [comment]
in 0.11 a position cannot be sold unless it has a sell on ta enabled flag
